# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898\u540d')),
                ('name', models.CharField(max_length=100, verbose_name='\u4f5c\u8005')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('type_id', models.IntegerField(default=1, verbose_name='\u6587\u7ae0\u7c7b\u522bID')),
                ('type', models.IntegerField(choices=[(1, 'Python'), (2, 'Django'), (3, '\u722c\u866b'), (4, 'Tornado'), (5, 'Flask'), (6, 'AI'), (7, '\u6570\u636e\u5e93'), (8, '\u5176\u4ed6')], verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('comments_nums', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
