# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 14:39
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
